import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/layout";
import banner from "@/image/Arcane_Announcement_Banner.jpg";
import { AiFillStar } from "react-icons/ai";
import NewThisWeek from "@/components/newThisWeek";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Image
          alt=""
          src={banner}
          className=" absolute top-0 right-0 bg-transparent h-full w-full object-cover -z-10"
        />
        <div className="w-full h-full flex flex-col justify-end text-sm text-gray-300 md:bg-gradient-to-r from-black via-transparent to-transparent ">
          <div className=" w-full  p-4 md:ml-16 md:w-96 md:mb-16">
            <h1 className=" text-xl mb-3 font-bold">Peaky Blinders</h1>
            <p className="text-slate-400 mb-6">
              Tommy Shelby, a dangerous man, leads the Peaky Blinders, a gang
              based in Birmingham. Soon, Chester Campbell, an inspector, decides
              to nab him and put an end to the criminal activities.
            </p>
            <div className="flex gap-1 mb-1">
              <AiFillStar />
              8.0/10
            </div>
            <div className=" mb-6">
              <p>
                <span className=" text-red-600">2B+</span>Stream
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-4">
              <button className="bg-rose-500 hover:bg-rose-700 text-white py-2 px-4 rounded sm:w-36">
                Play
              </button>
              <button className=" bg-slate-400 hover:bg-slate-500 text-gray-900  py-2 px-4 rounded sm:w-36">
                Watch Trailer
              </button>
            </div>
          </div>
          <div className="md:pl-16 flex flex-col p-4 bg-gradient-to-b from-transparent via-black to-black">
            <NewThisWeek />
            <NewThisWeek />
          </div>
        </div>
      </Layout>
    </>
  );
}
